Repository joaocarmo/i18n-postal-address, pull requests merged in 2022-03, with the labels that each got.

#31 [Feat] Miscellaneous changes to the repo
  .editorconfig
  README.md
  package.json
  yarn.lock
Labels: enhancement

#28 Using 'AddressObject' directly
  lib/postal-address.ts
  lib/types/address-format.ts
Labels: enhancement

#32 [Fix] The TypeScript types and tests
  lib/__tests__/address-formats.test.ts
  lib/__tests__/countries.test.ts
  lib/__tests__/object-initial-state.test.ts
  lib/__tests__/postal-address.test.ts
  lib/__tests__/utils.test.ts
  lib/address-formats.ts
  lib/address-parsers.ts
  lib/address-transforms.ts
  lib/object-initial-state.ts
  lib/postal-address.ts
  lib/types/address-format.ts
  lib/types/postal-address.ts
  lib/utils.ts
Labels: bug

#33 [Ref] To remove the ts ignore tags
  lib/postal-address.ts
  lib/types/address-format.ts
  lib/utils.ts
  package.json
Labels: refactor

#34 [Feat] Add initial object
  lib/__tests__/postal-address.test.ts
  lib/address-parsers.ts
  lib/postal-address.ts
  lib/types/address-format.ts
  lib/types/postal-address.ts
  lib/utils.ts
Labels: feature, refactor, tests
