Repository joaocarmo/i18n-postal-address, pull requests merged in 2024-01, with the labels that each got.

#123 Expand address formats with additional countries
  lib/address-formats.ts
Labels: feature

#131 package supports ESM import declarations
  package.json
Labels: bug

#125 chore: migrate to pnpm
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .npmrc
  .nvmrc
  Dockerfile
  README.md
  package.json
  pnpm-lock.yaml
  yarn.lock
Labels: chore

#132 fix(ci): enable corepack and switch to pnpm for publishing
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: chore
